# Generated by Django 5.0.2 on 2024-02-21 13:51

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_member_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('enabled_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
