# Generated by Django 5.0.2 on 2024-02-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_member_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
    ]
