# Generated by Django 5.0.2 on 2024-02-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='secret_reply',
            field=models.BooleanField(choices=[('0', '공개'), ('1', '비공개')], default=0),
        ),
    ]
