# Generated by Django 5.0.2 on 2024-02-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0003_alter_reply_secret_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='secret_reply',
            new_name='reply_private_status',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='group_deep_number',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='group_number',
        ),
        migrations.AddField(
            model_name='reply',
            name='group_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_depth',
            field=models.BigIntegerField(default=1),
        ),
    ]
