# Generated by Django 5.0.2 on 2024-02-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0005_alter_reply_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='reply',
            managers=[
            ],
        ),
    ]
